### ISSUE TITLE
Errors with the surgery list caused by RJW linkage patch.

### ISSUE THREAD

**Issue by StarFruit692093** [LunaGlaze/RimWorld-BiotechnologyReforgedFlesh-Anomaly#1] opened 2024-12-23 19:17 UTC
Caused by recipes issues.

Here is the log that appeared when I pressed add bill.

Probably not this but it appeared when I pressed add bill.

Exception in BreadthFirstTraverse: System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
[Ref 1D39E184]
 at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
 at System.Reflection.Assembly.GetTypes () [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
 at rjw.Hediff_BasePregnancy+<>c.<get_hediffOfClass>b__56_0 (System.Reflection.Assembly a) [0x00000] in <93dd1e67b1d0419eb9f5f0edd63e0728>:0 
 at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].MoveNext () [0x00051] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
 at rjw.Hediff_BasePregnancy.get_hediffOfClass () [0x00081] in <93dd1e67b1d0419eb9f5f0edd63e0728>:0 
 at rjw.Hediff_BasePregnancy.KnownPregnancies () [0x00000] in <93dd1e67b1d0419eb9f5f0edd63e0728>:0 
 at rjw.PawnExtensions.IsPregnant (Verse.Pawn pawn, System.Boolean mustBeVisible) [0x0005a] in <93dd1e67b1d0419eb9f5f0edd63e0728>:0 
     - POSTFIX rjw_genes: Void RJWLoveFeeding.MultiplePregnancies:Postfix(Boolean& __result, Pawn pawn, Boolean mustBeVisible)
 at rjw.PATCH_PawnUtility_FertileMateTarget.Prefix (Verse.Pawn male, Verse.Pawn female, System.Boolean& __state) [0x00000] in <93dd1e67b1d0419eb9f5f0edd63e0728>:0 
 at RimWorld.PawnUtility.FertileMateTarget (Verse.Pawn male, Verse.Pawn female) [0x00025] in <69945a8ed6c540cf90b578de735e0605>:0 
     - PREFIX rjw: Boolean rjw.PATCH_PawnUtility_FertileMateTarget:Prefix(Pawn male, Pawn female, Boolean& __state)
     - POSTFIX rjw: Boolean rjw.PATCH_PawnUtility_FertileMateTarget:Postfix(Boolean __result, Boolean& __state, Pawn male, Pawn female)
     - POSTFIX rjw: Boolean rjw.PATCH_PawnUtility_FertileMateTarget_MateReject:Postfix(Boolean __result, Pawn male, Pawn female)
 at RimWorld.JobGiver_Mate+<>c__DisplayClass0_0.<TryGiveJob>b__0 (Verse.Thing t) [0x00042] in <69945a8ed6c540cf90b578de735e0605>:0 
 at Verse.RegionProcessorClosestThingReachable.ProcessThing (Verse.Region reg, Verse.Thing t) [0x00080] in <69945a8ed6c540cf90b578de735e0605>:0 
 at Verse.RegionProcessorClosestThingReachable.RegionProcessor (Verse.Region reg) [0x0006c] in <69945a8ed6c540cf90b578de735e0605>:0 
 at Verse.RegionTraverser+BFSWorker.BreadthFirstTraverseWork (Verse.Region root, Verse.RegionEntryPredicate entryCondition, Verse.RegionProcessor regionProcessor, System.Int32 maxRegions, Verse.RegionType traversableRegionTypes) [0x00054] in <69945a8ed6c540cf90b578de735e0605>:0 
 at Verse.RegionTraverser.BreadthFirstTraverse (Verse.Region root, Verse.RegionEntryPredicate entryCondition, Verse.RegionProcessor regionProcessor, System.Int32 maxRegions, Verse.RegionType traversableRegionTypes) [0x00044] in <69945a8ed6c540cf90b578de735e0605>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch1 (string)
Verse.RegionTraverser:BreadthFirstTraverse (Verse.Region,Verse.RegionEntryPredicate,Verse.RegionProcessor,int,Verse.RegionType)
Verse.RegionTraverser:BreadthFirstTraverse (Verse.Region,Verse.RegionProcessorDelegateCache,int,Verse.RegionType)
Verse.GenClosest:RegionwiseBFSWorker_NewTemp (Verse.IntVec3,Verse.Map,Verse.ThingRequest,Verse.AI.PathEndMode,Verse.TraverseParms,System.Predicate`1<Verse.Thing>,System.Func`2<Verse.Thing, single>,int,int,single,int&,Verse.RegionType,bool,bool)
Verse.GenClosest:ClosestThingReachable_NewTemp (Verse.IntVec3,Verse.Map,Verse.ThingRequest,Verse.AI.PathEndMode,Verse.TraverseParms,single,System.Predicate`1<Verse.Thing>,System.Collections.Generic.IEnumerable`1<Verse.Thing>,int,int,bool,Verse.RegionType,bool,bool)
Verse.GenClosest:ClosestThingReachable (Verse.IntVec3,Verse.Map,Verse.ThingRequest,Verse.AI.PathEndMode,Verse.TraverseParms,single,System.Predicate`1<Verse.Thing>,System.Collections.Generic.IEnumerable`1<Verse.Thing>,int,int,bool,Verse.RegionType,bool)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:RimWorld.JobGiver_Mate.TryGiveJob_Patch2 (RimWorld.JobGiver_Mate,Verse.Pawn)
Verse.AI.ThinkNode_JobGiver:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_ChancePerHour:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_SubtreesByTag:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.AI.Pawn_JobTracker.DetermineNextJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.ThinkTreeDef&,bool)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Glue:AbiFixup<Verse.AI.ThinkResult Verse.AI.Pawn_JobTracker:DetermineNextJob(Verse.ThinkTreeDef&, System.Boolean),Verse.AI.ThinkResult Verse.AI.Pawn_JobTracker.DetermineNextJob_Patch1(Verse.AI.Pawn_JobTracker, Verse.ThinkTreeDef&, System.Boolean)> (Verse.AI.Pawn_JobTracker,Verse.AI.ThinkResult&,Verse.ThinkTreeDef&,bool)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch1 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.AI.Pawn_JobTracker.JobTrackerTick_Patch0 (Verse.AI.Pawn_JobTracker)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Pawn.Tick_Patch1 (Verse.Pawn)
Verse.TickList:Tick ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickManager.DoSingleTick_Patch4 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Game.UpdatePlay_Patch3 (Verse.Game)
Verse.Root_Play:Update ()

This is probably it

Exception filling tab RimWorld.ITab_Pawn_Health: System.NullReferenceException: Object reference not set to an instance of an object
[Ref 95FEA6E5]
 at rjw.Recipe_AddMultiPart.ValidFor (Verse.Pawn pawn) [0x00012] in <93dd1e67b1d0419eb9f5f0edd63e0728>:0 
 at rjw.Recipe_InstallPart.AvailableOnNow (Verse.Thing thing, Verse.BodyPartRecord part) [0x0000a] in <93dd1e67b1d0419eb9f5f0edd63e0728>:0 
 at Verse.RecipeWorker.AvailableReport (Verse.Thing thing, Verse.BodyPartRecord part) [0x00000] in <69945a8ed6c540cf90b578de735e0605>:0 
 at RimWorld.HealthCardUtility+<>c__DisplayClass27_0.<DrawMedOperationsTab>b__0 () [0x0003c] in <69945a8ed6c540cf90b578de735e0605>:0 
 at RimWorld.BillStack.DoListing (UnityEngine.Rect rect, System.Func`1[TResult] recipeOptionsMaker, UnityEngine.Vector2& scrollPosition, System.Single& viewHeight) [0x00059] in <69945a8ed6c540cf90b578de735e0605>:0 
 at RimWorld.HealthCardUtility.DrawMedOperationsTab (UnityEngine.Rect leftRect, Verse.Pawn pawn, Verse.Thing thingForMedBills, System.Single curY) [0x00063] in <69945a8ed6c540cf90b578de735e0605>:0 
 at RimWorld.HealthCardUtility.DrawHealthSummary (UnityEngine.Rect rect, Verse.Pawn pawn, System.Boolean allowOperations, Verse.Thing thingForMedBills) [0x0018c] in <69945a8ed6c540cf90b578de735e0605>:0 
     - PREFIX Adamas.Hospital: Void Hospital.Patches.AllowOperationsPatch+AllowOperationsOnPatients:Prefix(Pawn pawn, Boolean& allowOperations)
 at RimWorld.HealthCardUtility.DrawPawnHealthCard (UnityEngine.Rect outRect, Verse.Pawn pawn, System.Boolean allowOperations, System.Boolean showBloodLoss, Verse.Thing thingForMedBills) [0x000ae] in <69945a8ed6c540cf90b578de735e0605>:0 
 at RimWorld.ITab_Pawn_Health.FillTab () [0x0003d] in <69945a8ed6c540cf90b578de735e0605>:0 
 at Verse.InspectTabBase+<>c__DisplayClass19_0.<DoTabGUI>b__0 () [0x00039] in <69945a8ed6c540cf90b578de735e0605>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch1 (string)
Verse.Log:ErrorOnce (string,int)
Verse.InspectTabBase/<>c__DisplayClass19_0:<DoTabGUI>b__0 ()
Verse.ImmediateWindow:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

This is the last thing that appeared

Alignment was UpperCenter at end of frame.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch1 (string)
Verse.Log:ErrorOnce (string,int)
Verse.Text:StartOfOnGUI ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.UIRoot.UIRootOnGUI_Patch2 (Verse.UIRoot)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:RimWorld.UIRoot_Play.UIRootOnGUI_Patch2 (RimWorld.UIRoot_Play)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root.OnGUI_Patch1 (Verse.Root)

Hope this helps!

**Comment by StarFruit692093** [comment] 2024-12-23 19:18
I couldn't add the entire log but most of it was other mods and I don't think they are causing issues.

**Comment by LunaGlaze** [comment] 2024-12-24 02:32
Sorry, in my case everything is fine and there is not enough information in the error log for me to analyze exactly where the conflict is. All I can tell is that it seems to be an error caused by some mod patching the code of the rjw core mod or vanilla via Harmony.
If possible, I'd like you could to similarly submit a minimal list of mods as well where this issue occurs to help me reproduce the bug to determine the exact conflict for subsequent fixes. I'm still using 5.4.1 of rjw , so if you are using other versions or even community second-changed mods, it could be because of this.

**Comment by LyricaPrismriver** [comment] 2024-12-24 03:28
[Player.log](https://github.com/user-attachments/files/18235431/Player.log)
[20241224.zip](https://github.com/user-attachments/files/18235435/20241224.zip)
这是缩减到几乎只剩rjw及其附属和血肉重铸的列表以及日志，我新建殖民地仍然打不开手术清单，应该可以复现

[Player.log](https://github.com/user-attachments/files/18235538/Player.log)
[20241224-9mod.zip](https://github.com/user-attachments/files/18235540/20241224-9mod.zip)
这是缩减到只剩rjw和血肉重铸的列表以及日志

rjw的mod可以通过这个工具下载
https://www.loverslab.com/topic/231570-libidinous-loader-rjw-mod-loader-and-providers-list-100-mods-supported/
RimPy导出的pack
链接: https://pan.baidu.com/s/1ovo0BtK0hBscOmr12FBLzw?pwd=ivxt 提取码: ivxt

**Comment by StarFruit692093** [comment] 2024-12-24 05:17
[Player.log](https://github.com/user-attachments/files/18236044/Player.log)
I copied what that the other guy did I had no clue I could just copy a log here.
But this is the unfiltered log in all of it's glory!
I still do not know whats wrong but the only mods enabled right now are RJW and it's dependecys and Meatcore yet they still don't function together even though no other mods are enabled.
And strangenly they function fine when alone from each other.

**Comment by StarFruit692093** [comment] 2024-12-24 05:18
I have the most recent version of RJW and Meatcore and of course the depenedies of harmony and hugslib for rjw

**Comment by LunaGlaze** [comment] 2024-12-24 08:37
I think I probably know the problem, which is supposed to be caused by rjw completely resetting the code structure and naming in 5.5 or 5.6. This makes lower versions of all rjw extensions and linkages in regards to organs incompatible with higher versions.
But as far as I know there are still a lot of users who still haven't updated to the latest version (including me) and I don't know of any way to make them coexist.
The temporary solution now is to open the mod folder and delete all files in the 1.5/Mods/RJW directory, or roll back the RJW version.

**Comment by LunaGlaze** [comment] 2024-12-26 09:08
A fix for this issue has been pushed, so please confirm that the issue has been resolved. If the issue has been resolved, it will be closed.

**Closed as completed** 2024-12-27 05:38 UTC
Labels: bug
